export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const RESET_FORM_AFTER_ERROR = 'RESET_FORM_AFTER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER = 'LOGIN_USER';

export const USER_DETAIL_UPDATE = 'USER_DETAIL_UPDATE';
export const NEWU_CLEAR_EMAILS = 'NEWU_CLEAR_EMAILS';
export const NEWU_CLEAR_PASSWORDS = 'NEWU_CLEAR_PASSWORDS';
export const NEWU_CREATE_SUCCESS = 'NEWU_CREATE_SUCCESS';
export const NEWU_CREATE_USER = 'NEWU_CREATE_USER';  
export const NEWU_CLEAR_SCREEN = 'NEWU_CLEAR_SCREEN';           

export const NEARBY_AGENT_FETCH_SUCCESS = 'NEARBY_AGENT_FETCH_SUCCESS';
export const SET_MAP_LOOKUP_PROPERTY_ADDRESS = 'SET_MAP_LOOKUP_PROPERTY_ADDRESS';
export const SET_PROPERTY_ADDRESS = 'SET_PROPERTY_ADDRESS';

export const LOCATION_ALLOWED = 'LOCATION_ALLOWED';
export const NEW_LISTING_UPDATE = 'NEW_LISTING_UPDATE';
export const UPDATE_ADDRESS_LINE = 'UPDATE_ADDRESS_LINE';
export const SAVE_NEW_LISTING_SUCCESS = 'SAVE_NEW_LISTING_SUCCESS';
