export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const RESET_FORM_AFTER_ERROR = 'RESET_FORM_AFTER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER = 'LOGIN_USER';

export const USER_DETAIL_UPDATE = 'USER_DETAIL_UPDATE';
export const NEWU_CLEAR_EMAILS = 'NEWU_CLEAR_EMAILS';
export const NEWU_CLEAR_PASSWORDS = 'NEWU_CLEAR_PASSWORDS';
export const NEWU_CREATE_SUCCESS = 'NEWU_CREATE_SUCCESS';
export const NEWU_CREATE_USER = 'NEWU_CREATE_USER';  
export const NEWU_CLEAR_SCREEN = 'NEWU_CLEAR_SCREEN';           
